# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause


---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: srlinuxes.kne.srlinux.dev
spec:
  group: kne.srlinux.dev
  names:
    kind: Srlinux
    listKind: SrlinuxList
    plural: srlinuxes
    singular: srlinux
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.image
      name: Image
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Srlinux is the Schema for the srlinuxes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          license_key:
            description: license key from license secret that contains a license file
              for this Srlinux
            type: string
          metadata:
            type: object
          spec:
            description: SrlinuxSpec defines the desired state of Srlinux.
            properties:
              config:
                description: NodeConfig represents srlinux node configuration parameters.
                properties:
                  args:
                    items:
                      type: string
                    type: array
                  cert:
                    description: CertificateCfg represents srlinux certificate configuration
                      parameters.
                    properties:
                      cert_name:
                        description: Certificate name on the node.
                        type: string
                      common_name:
                        description: Common name to set in the cert.
                        type: string
                      key_name:
                        description: Key name on the node.
                        type: string
                      key_size:
                        description: RSA keysize to use for key generation.
                        format: int32
                        type: integer
                    type: object
                  command:
                    items:
                      type: string
                    type: array
                  config_data_present:
                    description: When set to true by kne, srlinux controller will
                      attempt to mount the file with startup config to the pod
                    type: boolean
                  config_file:
                    description: Startup configuration file name for the pod. Set
                      in the kne topo and created by kne as a config map
                    type: string
                  config_path:
                    description: Mount point for configuration inside the pod. Should
                      point to a dir that contains ConfigFile
                    type: string
                  entry_command:
                    description: Specific entry point command for accessing the pod.
                    type: string
                  env:
                    additionalProperties:
                      type: string
                    description: Map of environment variables to pass into the pod.
                    type: object
                  image:
                    type: string
                  sleep:
                    format: int32
                    type: integer
                type: object
              constraints:
                additionalProperties:
                  type: string
                type: object
              model:
                description: Model encodes SR Linux variant (ixr-d3, ixr-6e, etc)
                type: string
              num-interfaces:
                type: integer
              version:
                description: Version may be set in kne topology as a mean to explicitly
                  provide version information in case it is not encoded in the image
                  tag
                type: string
            type: object
          status:
            description: SrlinuxStatus defines the observed state of Srlinux.
            properties:
              image:
                description: Image used to run srlinux pod
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
