apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meshnet
commonLabels:
  app: meshnet
resources:
- namespace.yaml
- serviceaccount.yaml
- crd.yaml
- rbac.yaml
- daemonset.yaml
