---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshnet-clusterrole
rules:
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies
    verbs: ["*"]
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies/status
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshnet-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: meshnet-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: meshnet
