apiVersion: v1
kind: ConfigMap
metadata:
  name: ixiatg-release-config
  namespace: ixiatg-op-system
data:
  versions: |
    {
      "release": "0.0.1-9999",
      "images": [
            {
                "name": "controller",
                "path": "ghcr.io/open-traffic-generator/keng-controller",
                "tag": "0.0.1-5308"
            },
            {
                "name": "gnmi-server",
                "path": "ghcr.io/open-traffic-generator/otg-gnmi-server",
                "tag": "1.12.8"
            },
            {
                "name": "traffic-engine",
                "path": "ghcr.io/open-traffic-generator/ixia-c-traffic-engine",
                "tag": "1.6.0.85"
            }
        ]
    }
