apiVersion: v1
kind: ConfigMap
metadata:
  name: ixiatg-release-config
  namespace: ixiatg-op-system
data:
  versions: |
    {
      "release": "0.0.1-3698",
      "images": [
            {
                "name": "controller",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-controller",
                "tag": "0.0.1-3698"
            },
            {
                "name": "gnmi-server",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-gnmi-server",
                "tag": "1.10.5"
            },
            {
                "name": "traffic-engine",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-traffic-engine",
                "tag": "1.6.0.19"
            },
            {
                "name": "protocol-engine",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine",
                "tag": "1.00.0.252"
            }
        ]
    }
